# Generated by dossier-release for 0.7.0. Publish it to the
# kylebegeman/homebrew-tap repository with the matching release assets.
class Dossier < Formula
  desc "Turn one JSON model into one self-contained HTML dossier"
  homepage "https://github.com/kylebegeman/dossier"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/kylebegeman/dossier/releases/download/v0.7.0/dossier_0.7.0_darwin_arm64.tar.gz"
      sha256 "799ff4c99b6fa8fac0094ea7e226c6da5f44291aaf5d2fe0e16c8fcdb4748857"
    end
    on_intel do
      url "https://github.com/kylebegeman/dossier/releases/download/v0.7.0/dossier_0.7.0_darwin_amd64.tar.gz"
      sha256 "6a81a6d1513bec08759a427e80bebb57f23445253ef88c2f75751768aded489e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kylebegeman/dossier/releases/download/v0.7.0/dossier_0.7.0_linux_arm64.tar.gz"
      sha256 "e512847b5b89d0f7647faf29df884a8866ece2ae96dda0a1d350dd0276fc9398"
    end
    on_intel do
      url "https://github.com/kylebegeman/dossier/releases/download/v0.7.0/dossier_0.7.0_linux_amd64.tar.gz"
      sha256 "34e0c105d2f043dd3751edab51adc700eaa6052623a8bade7bf78817be291e72"
    end
  end

  def install
    bin.install "dossier"
  end

  test do
    assert_match "dossier #{version}", shell_output("#{bin}/dossier --version")
    system bin/"dossier", "init", "brainstorm", "--title", "Brew test", "--out", testpath
    system bin/"dossier", "build", testpath/"brew-test.dossier.json"
    assert_path_exists testpath/"brew-test.html"
  end
end
