# Generated by dossier-release for 0.7.3. Publish it to the
# kylebegeman/homebrew-tap repository with the matching release assets.
class Dossier < Formula
  desc "Turn one JSON model into one self-contained HTML dossier"
  homepage "https://github.com/kylebegeman/dossier"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/kylebegeman/dossier/releases/download/v0.7.3/dossier_0.7.3_darwin_arm64.tar.gz"
      sha256 "751ea4475b2f86bfaa895a171d8a981e0840447a2c622f0031aaf0107e7fe20a"
    end
    on_intel do
      url "https://github.com/kylebegeman/dossier/releases/download/v0.7.3/dossier_0.7.3_darwin_amd64.tar.gz"
      sha256 "2729a6c62e472f9ec898ab0cbc45c59f5278f80f32b096d0868bf54e4eec389c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kylebegeman/dossier/releases/download/v0.7.3/dossier_0.7.3_linux_arm64.tar.gz"
      sha256 "aeab211585918b22d0e8b4282a309c241b410784e5a5d738e45e87b604583187"
    end
    on_intel do
      url "https://github.com/kylebegeman/dossier/releases/download/v0.7.3/dossier_0.7.3_linux_amd64.tar.gz"
      sha256 "a41ccb398bdf6a68a09c8b081eed0d9b8aab6a3196ff8c2cf0678c8d47011476"
    end
  end

  def install
    bin.install "dossier"
  end

  test do
    assert_match "dossier #{version}", shell_output("#{bin}/dossier --version")
    system bin/"dossier", "init", "brainstorm", "--title", "Brew test", "--out", testpath
    system bin/"dossier", "build", testpath/"brew-test.dossier.json"
    assert_path_exists testpath/"brew-test.html"
  end
end
