# Generated by dossier-release for 0.7.2. Publish it to the
# kylebegeman/homebrew-tap repository with the matching release assets.
class Dossier < Formula
  desc "Turn one JSON model into one self-contained HTML dossier"
  homepage "https://github.com/kylebegeman/dossier"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/kylebegeman/dossier/releases/download/v0.7.2/dossier_0.7.2_darwin_arm64.tar.gz"
      sha256 "e5bd5b686091a37906e02860894d15a045603b4383efbe6bcb426d499861d792"
    end
    on_intel do
      url "https://github.com/kylebegeman/dossier/releases/download/v0.7.2/dossier_0.7.2_darwin_amd64.tar.gz"
      sha256 "429cb74980dde2032b4dc500bea71d31aa39a96d62cb60255a8ba1135e93ca8b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kylebegeman/dossier/releases/download/v0.7.2/dossier_0.7.2_linux_arm64.tar.gz"
      sha256 "3e0c6c7661d5fa67dedea141465da74c95506cc06b7dc0ee6a7437ed0aa70e67"
    end
    on_intel do
      url "https://github.com/kylebegeman/dossier/releases/download/v0.7.2/dossier_0.7.2_linux_amd64.tar.gz"
      sha256 "012b0f9f07800ee32d7d58d903b19a644c3b79723f597bc62f39fd2b05f5a71e"
    end
  end

  def install
    bin.install "dossier"
  end

  test do
    assert_match "dossier #{version}", shell_output("#{bin}/dossier --version")
    system bin/"dossier", "init", "brainstorm", "--title", "Brew test", "--out", testpath
    system bin/"dossier", "build", testpath/"brew-test.dossier.json"
    assert_path_exists testpath/"brew-test.html"
  end
end
